export const MAINPAGE_ROUTE = '/'
export const TREES_ROUTE = '/trees'
export const EXPLANATION_ROUTE = '/explanation'
export const SETTINGS_ROUTE = '/settings'
export const EXAMPLES_ROUTE = '/examples'